In [16]:
# soit un jeu de données décrivant l'autonomie d'ordinateurs
import pandas as pd
don=pd.DataFrame(['une autonomie de 10h',"jusqu'à 12h30 d'autonomie","1 heure","48 heures en veille et 12h en utilisation","une autonomie meilleure que l'iphone X","blabla"])

In [17]:
don.columns=['autonomie']

In [3]:
don

                                   autonomie
0                       une autonomie de 10h
1                  jusqu'à 12h30 d'autonomie
2                                    1 heure
3  48 heures en veille et 12h en utilisation
4     une autonomie meilleure que l'iphone X
5                                     blabla

In [ ]:
# étape 1 écrivez une fonction utilisant une regex de type search et tester sur en entrée une chaine de caractères

In [12]:
import re 
import unidecode

def chercheautonomie(str_enentree):
    ch = unidecode.unidecode(str_enentree.lower())
    ch = str_enentree.replace("heures","h").replace("heure","h")
    if re.search("[0-9]{1,2}\s{0,1}[h]\s{0,1}[0-9]{1,2}",ch):
        return re.sub("([0-9]{1,2})\s{0,1}[h]\s{0,1}([0-9]{1,2})","-autonomie:\\1h\\2-",ch)
    elif re.search("[0-9]{1,2}\s{0,1}[h]",ch):
        return re.sub("([0-9]{1,2})\s{0,1}[h]","-autonomie:\\1-",ch)
    else:
        return str_enentree

In [50]:
chaine1="une autonomie de 10h"
chercheautonomie(chaine1)

'une autonomie de -autonomie:10-'

In [ ]:
# étape 2 si la fonction vous convient appliquer là à la colonne du dataframe avec la fonction apply

In [23]:
don['autonomie']=don['autonomie'].apply(lambda x:chercheautonomie(x).split('-'))

In [51]:
don

                                           autonomie
0                [une autonomie de , autonomie:10, ]
1          [jusqu'à , autonomie:12h30,  d'autonomie]
2                                  [, autonomie:1, ]
3  [, autonomie:48,  en veille et , autonomie:12,...
4           [une autonomie meilleure que l'iphone X]
5                                           [blabla]

In [53]:
don2=don.explode('autonomie')
don2

                                autonomie
0                       une autonomie de
0                            autonomie:10
0
1                                jusqu'à
1                         autonomie:12h30
1                             d'autonomie
2
2                             autonomie:1
2
3
3                            autonomie:48
3                           en veille et
3                            autonomie:12
3                          en utilisation
4  une autonomie meilleure que l'iphone X
5                                  blabla

In [54]:
don2=don2[ don2.autonomie.str.contains(":")]
don2

         autonomie
0     autonomie:10
1  autonomie:12h30
2      autonomie:1
3     autonomie:48
3     autonomie:12

In [55]:
don2['autonomie']=don2['autonomie'].apply(lambda x:x.split(':'))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [47]:
don2

            autonomie
0     [autonomie, 10]
1  [autonomie, 12h30]
2      [autonomie, 1]
3     [autonomie, 48]
3     [autonomie, 12]

In [48]:
don2=don2['autonomie'].apply(lambda x: x[1])
don2

0       10
1    12h30
2        1
3       48
3       12
Name: autonomie, dtype: object

In [ ]:
# étape 3 mettre le code dans un py pour le modulariser
# C:\Users\dgr\OneDrive - Publicis Groupe\Documents\Formations\SCU Python\NEW\pgm avance\modules