# ASTUCES PANDAS

In [3]:
import os # commandes systèmes pour definir le rép de travail
repertoire = "C:/Users/dgr/OneDrive - Publicis Groupe/Documents/Formations/SCU Python/NEW/data"
os.chdir(repertoire)
os.getcwd()

'C:\\Users\\dgr\\OneDrive - Publicis Groupe\\Documents\\Formations\\SCU Python\\NEW\\data'

In [5]:
import pandas as pd 
# pandas permet de lire un json et de créer une table
iris = pd.read_json("iris.json")
iris.columns # index des col

Index(['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species'], dtype='object')

In [6]:
#import wget # téléchargement
#url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'  
#wget.download(url,out="irisHTTP.csv")

In [7]:
#lire un fichier csv
iris = pd.read_csv("irisHTTP.csv",sep=',',header=None,encoding='latin-1')
# on définit les colonnes, columns est un attribut du df qu'on vient écraser
iris.columns = ['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth', 'species']

In [8]:

# structure
iris.info()
iris.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   petalLength  150 non-null    float64
 1   petalWidth   150 non-null    float64
 2   sepalLength  150 non-null    float64
 3   sepalWidth   150 non-null    float64
 4   species      150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

petalLength    float64
petalWidth     float64
sepalLength    float64
sepalWidth     float64
species         object
dtype: object

In [9]:
# résumé incluant les données quali et quanti
datafr=iris.describe(include='all')
iris.describe(include='all').to_csv("summary_iris.csv")
iris.describe(include='all').to_json("summary_iris.json")
stat=iris.describe(include='all') # les chaines sont typés en object

In [10]:

# data management
iris.drop(['petalLength', 'petalWidth'],axis=1) # drop nouvelle variable
iris.rename(columns={'petalLength':'petaleLongueur'}) # nécessite inplace=True 
iris.rename(columns={'petalLength':'petaleLongueur'},inplace=True)
iris=iris.rename(columns={'petalWidth':'petaleLargeur'}) # ou 
liste_especes=list(iris["species"].unique()) # liste des modalités

In [11]:
# arrondir et convertir en integer
iris.petaleLongueur.round(0).astype(int)

0      5
1      5
2      5
3      5
4      5
      ..
145    7
146    6
147    6
148    6
149    6
Name: petaleLongueur, Length: 150, dtype: int32

In [12]:
# species est une donnée qualitative, on peut la typer en category
iris.species=iris.species.astype('category')
stat=iris.describe(include='all') # les chaines sont typés en object

In [13]:
# A partir du fichier csv, il y a un préfixe dans la col species
# extraire le deuxieme mot dans la col species
type(iris['species'].str.split('-')) # => Series en sortie
type(iris['species'].str.split('-')[0]) # => list
iris['species2'] = iris['species'].str.split('-')
# species2 c'est un vecteur de liste
iris['species2'] [0][1] # premiere ligne puis seconde col

'setosa'

In [14]:
# donc pour extraire la deuxième partie de la liste
# la fonction apply applique à toutes les lignes la fonction déclaré dans le lambda
iris['species2'] = iris['species'].str.split('-').apply(lambda x: x[1])
iris['flagvirginica'] = (iris.species2 == 'virginica')

In [15]:
# tableau de fréquence
iris.species2.value_counts()

virginica     50
versicolor    50
setosa        50
Name: species2, dtype: int64

In [16]:
# pct :applique à chaque ligne la fonction lambda
iris.species2.value_counts().apply(lambda x: x/len(iris))
help(pd.value_counts)
iris.species2.value_counts(normalize=True) # il est plus simple de faire

Help on function value_counts in module pandas.core.algorithms:

value_counts(values, sort: bool = True, ascending: bool = False, normalize: bool = False, bins=None, dropna: bool = True) -> 'Series'
    Compute a histogram of the counts of non-null values.

    Parameters
    ----------
    values : ndarray (1-d)
    sort : bool, default True
        Sort by values
    ascending : bool, default False
        Sort in ascending order
    normalize: bool, default False
        If True then compute a relative histogram
    bins : integer, optional
        Rather than count values, group them into half-open bins,
        convenience for pd.cut, only works with numeric data
    dropna : bool, default True
        Don't include counts of NaN

    Returns
    -------
    Series

virginica     0.333333
versicolor    0.333333
setosa        0.333333
Name: species2, dtype: float64

## COMMENT ACCEDER AUX LIGNES ET AUX COL d'un DATAFRAME: slicing

In [24]:
# sur une dataframe toutes les lignes d'une col, renvoie un objet serie
iris = pd.read_csv("irisHTTP.csv",sep=',',header=None,encoding='latin-1')
# on définit les colonnes, columns est un attribut du df qu'on vient écraser
iris.columns = ['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth', 'species']
iris["petalLength"] # ou
iris.petalLength

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: petalLength, Length: 150, dtype: float64

In [25]:
# pour accéder au ligne du coup , comme c'un objet series on met des crochets
# ici accès par l'index en col et lindice en ligne
print(iris["petalLength"][[0,149]])

0      5.1
149    5.9
Name: petalLength, dtype: float64

In [26]:
# la notation mat ne marche pas sur une DF, mais sur une matrice oui
test=iris[:,"petalLength"] ;
 test=iris[:,0]  # unhashable type: 'slice'
iris.values[:,0:4] # en matrice : ca marche
type(iris.values)

IndentationError: unexpected indent (<ipython-input-26-932221daa5b0>, line 3)

In [27]:
# loc réfère aux index et iloc aux indices
iris.loc[0] # première ligne
iris.loc[0,"petalLength"] # première ligne et col petalLength

5.1

In [28]:
# par contre iris.loc[0,0] ne marche pas car l'index en col est le nom de la var pas un indice
iris.iloc[0,0]  # ligne 1 , col 1
iris.iloc[:,0]  # ligne toutes, col 1
iris.loc[:,"petalLength"] # ligne toutes, col petalLength

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: petalLength, Length: 150, dtype: float64

In [29]:

# à noter que quand on slice sur les index le terme de droite est inclus!
iris.loc[0:1,"petalLength"]
# à noter que quand on slice sur les indices le terme de droite est exclus!
iris.iloc[0:1,0]

0    5.1
Name: petalLength, dtype: float64

In [30]:

# pour indiquer des listes, il faut créer une liste entre []
iris.loc[:,['petalLength', 'petalWidth', 'sepalLength', 'sepalWidth']]

     petalLength  petalWidth  sepalLength  sepalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [31]:


# accès en indices
iris.iloc[:,[0,1,2,3]]
iris.iloc[:,range(4)]

     petalLength  petalWidth  sepalLength  sepalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [32]:

# attention, accès en index: avec 2 bornes, la seconde est incluse contrairement aux accès par indices
iris.iloc[0:149,0] # 149 lignes
iris.loc[0:149:,"petalLength"] # 150 lignes
(iris.iloc[0:149,0].shape == iris.loc[0:149:,"petalLength"].shape) # => False

False