# LIRE UN FICHIER ET CORRIGER LES ANOMALIES

## Import des packages

In [2]:
import os
import pandas as pd
import re

## STEP 1 : PANDAS

In [4]:
rep="../../../data/exercice_RH"
data_input = rep + "/JOBS_jouet_aparse.csv"

In [5]:
data_df = pd.read_csv(
    data_input,
    delimiter=';',
    decimal=",",
    encoding='utf-8',
    on_bad_lines='warn'   # remplace error_bad_lines=False
)

C:\Users\wilverde\AppData\Local\Temp\ipykernel_40784\43145640.py:1: ParserWarning: Skipping line 3: expected 3 fields, saw 6

  data_df = pd.read_csv(

In [6]:
# Afficher les premières lignes 
data_df.head(10)

         ID Job    Dat.Arrv.Job
0      1001   1      01/01/2011
1  TESTTEST  \t             NaN
2      1001  \t      01/06/2013
3       999   2  \r\n01/06/2013
4      1002   1      01/06/2012
5      1002   1    01\t/06/2012
6      1003   1      01/06/2012
7      1004   1      01/06/2012
8      1005   1      01/06/2012
9      1007   1      01/06/2012

Lister les anomalies ...

## STEP 2 : OPEN AS FILE

In [ ]:
# Ouvrir le fichier en mode lecture
f = open(data_input, "rt")

In [ ]:
# Lire toutes les lignes
l=f.readlines()

In [ ]:
# Afficher les 10 premières lignes
l[0:20]

['\ufeffID;Job;Dat.Arrv.Job\n',
 '1001;1;01/01/2011\n',
 'TESTTEST;;;;;\n',
 'TESTTEST;\t\n',
 '1001;\t;01/06/2013\n',
 '"999";"2";"\n',
 '01/06/2013"\n',
 '1002;1;01/06/2012\n',
 '1002;1;01\t/06/2012\n',
 '1003;1;01/06/2012\n',
 '1004;1;01/06/2012\n',
 '1005;1;01/06/2012\n',
 '1007;1;01/06/2012\n',
 '1008;1;01/06/2012\n',
 '1009;1;01/06/2012\n',
 '1010;1;01/06/2012\n',
 '1011;1;01/06/2012\n',
 '1012;1;01/06/2012\n',
 '1013;1;01/06/2012\n',
 '1014;1;01/06/2012\n']

Lister les anomalies ...

## STEP 3 : Utiliser les regex pour corriger toutes les anomalies identifiées

In [ ]:
data_output = rep+"/out.txt"

In [ ]:
# ouvrir le fichier data_output en mode écriture
fout = open(data_output, "wt")

In [ ]:
# Parcourir chaque ligne pour lui appliquer l'ensemble des correctifs (en partant de l)
nom_columns = []
nb_columns = 0
for index, text in enumerate(l):
    if index == 0 : # si première ligne, on identifie le nombre de colonnes
        nom_columns = text.split(";")
        nb_columns = len(nom_columns)
    text_propre = text.replace('\t','') \
                        .replace('\n','') \
                        .replace('"', '') \
                        .replace('\ufeff','')
    text_propre_split = text_propre.split(";")
    while len(text_propre_split)<3:
        text_propre_split.append("")
    text_propre_final = ";".join(text_propre_split[0:3])+'\n'
    #ecrit la ligne propre
    fout.write(text_propre_final)

In [ ]:
# On ferme les 2 fichiers ouverts
f.close()
fout.close()

In [ ]:
# verif
fin = open(data_output, "rt")

In [ ]:
l=fin.readlines()
l[0:20]

['ID;Job;Dat.Arrv.Job\n',
 '1001;1;01/01/2011\n',
 'TESTTEST;;\n',
 'TESTTEST;;\n',
 '1001;;01/06/2013\n',
 '999;2;\n',
 '01/06/2013;;\n',
 '1002;1;01/06/2012\n',
 '1002;1;01/06/2012\n',
 '1003;1;01/06/2012\n',
 '1004;1;01/06/2012\n',
 '1005;1;01/06/2012\n',
 '1007;1;01/06/2012\n',
 '1008;1;01/06/2012\n',
 '1009;1;01/06/2012\n',
 '1010;1;01/06/2012\n',
 '1011;1;01/06/2012\n',
 '1012;1;01/06/2012\n',
 '1013;1;01/06/2012\n',
 '1014;1;01/06/2012\n']

In [ ]:
fin.close()

## STEP 4 : pandas

In [ ]:
# Lire le nouveau fichier avec pandas
data_df = pd.read_csv(data_output, 
                   delimiter=';', 
                   decimal=",", 
                   encoding = 'utf-8')

In [ ]:
# Afficher les 10 premières lignes
data_df.head(10)

           ID  Job Dat.Arrv.Job
0        1001  1.0   01/01/2011
1    TESTTEST  NaN          NaN
2    TESTTEST  NaN          NaN
3        1001  NaN   01/06/2013
4         999  2.0          NaN
5  01/06/2013  NaN          NaN
6        1002  1.0   01/06/2012
7        1002  1.0   01/06/2012
8        1003  1.0   01/06/2012
9        1004  1.0   01/06/2012